from googletrans import Translator
translator = Translator()
# print((translator.translate('안녕하세요.')).text)
print('af', translator.translate('This job requires manual data entry in English.', dest='af').text)
print('zh', translator.translate('This job requires manual data entry in English.', dest='zh-tw').text)
print('cn', translator.translate('This job requires manual data entry in English.', dest='zh-cn').text)
print('ar', translator.translate('This job requires manual data entry in English.', dest='ar').text)
print('ur', translator.translate('This job requires manual data entry in English.', dest='ur').text)
print('vi', translator.translate('This job requires manual data entry in English.', dest='vi').text)
print('zu', translator.translate('This job requires manual data entry in English.', dest='zu').text)
# print(translator.translate('veritas lux mea', src='la'))